let x = document.getElementById("png1")
    z = document.getElementById("png2")
    y = document.getElementById("png3")
    c = document.getElementById("png4")
    v = document.getElementById("png5")
x.setAttribute("class","im1")
z.setAttribute("class","im2")
y.setAttribute("class","im3")
c.setAttribute("class","im4")
v.setAttribute("class","im5")