let userName=prompt("What you name?")
    userAge=prompt("Hello,"+userName+", how old are you?")
    userWorkage=prompt(userName+", how old are you working with IT?")
    userPlace=prompt(userName+", where you from?")
    userStr=prompt(userName+", what are your strengths?")
    userWeak=prompt(userName+", what are your weaknesses?")
    userPay=prompt(userName+", what level of salary will suit you?")
    userChild=prompt(userName+", do you have children?")
    userHabits=prompt(userName+", do you have bad habits?")
    userCandidates=prompt(userName+", why should we hire you for this job? How are you different from other candidates?")
    userProject=prompt(userName+", what's your last major project?")
    userProcessing=prompt(userName+", how do you feel about processing?")

    console.log(userName)
    console.log(userAge)
    console.log(userWorkage)
    console.log(userPlace)
    console.log(userStr)
    console.log(userWeak)
    console.log(userPay)
    console.log(userChild)
    console.log(userHabits)
    console.log(userCandidates)
    console.log(userProject)
    console.log(userProcessing)